IWMS/IWMS/urls.py
from django.contrib import admin, auth
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('ProjectManagement/', include('ProjectManagement.urls')),
    path('admin/', admin.site.urls),
]+static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

IWMS/ProjectManagement/urls.py
from django.urls import path
from . import views 

app_name='ProjectManagement'

urlpatterns = [
    path('history/<str:MODEL>/', views.history_view, name='history_view'),
    path('ajax_server', views.ajax_server, name='ajax_server'),
    path('real_time/<str:MODEL>/', views.real_time_view, name='real_time'),
    path('login/', views.login_input, name='login_input'),
    path('login_action/', views.log_in, name='login_action'),
    path('logout/', views.log_out, name='log_out'),
    path('index/', views.index, name='index')
]

IWMS/ProjectManagement/models.py
from django.db import models

# Create your models here.

class Station(models.Model):
    #工位
    name = models.CharField(max_length=50, null = False, unique=True, help_text='工位名称')
    description = models.TextField(max_length=200, blank= True, null= True, help_text='工位描述')
    def __str__(self):
        return self.name

class Current(models.Model):
    Station = models.ForeignKey(Station, on_delete=models.CASCADE, null=False, blank=False)
    date_time = models.DecimalField(max_digits= 10, decimal_places=0)
    value = models.FloatField()

class Voltage(models.Model):
    Station = models.ForeignKey(Station, on_delete=models.CASCADE, null = False, blank=False)
    date_time = models.DecimalField(max_digits= 10, decimal_places=0)
    value = models.FloatField()

class Sound(models.Model):
    Station = models.ForeignKey(Station, on_delete=models.CASCADE, null=False, blank=False)
    date_time = models.DecimalField(max_digits= 10, decimal_places=0)
    value = models.FloatField()

class PoolImg(models.Model):
    Station = models.ForeignKey(Station, on_delete=models.CASCADE, null=False, blank = False)
    date_time = models.DecimalField(max_digits= 10, decimal_places=0)
    value = models.TextField() #base64数据

IWMS/ProjectManagement/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse, Http404
from ProjectManagement.models import Voltage, Station, Current, Sound, PoolImg
import datetime, time
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.clickjacking import xframe_options_exempt
# Create your views here.
time_pattern = [
    "%Y-%m-%d %H:%M:%S",
    "%Y-%m-%d %H:%M",
    "%Y-%m-%d ",
    "%m-%d %H:%M"
]
models_dict = {
    'Station':Station,
    'Voltage':Voltage,
    'Current':Current,
    'PoolImg':PoolImg,
    'Sound':Sound
}


def login_input(request):
    return render(request, "ProjectManagement/login.html")

def log_in(request):
    username= request.POST['username']
    passwd = request.POST['passwd']
    user = authenticate(request, username=username, password=passwd)
    print(request)
    if user is not None:
        login(request, user)
        return redirect("/ProjectManagement/index/")
    else:
        return render(request,"ProjectManagement/login.html", {'error_massage':'用户名或密码错误'})

@login_required
def index(request):
    print(request.user.username)
    return render(request, 'ProjectManagement/index.html',{'user':request.user})



@login_required
def log_out(request):
    logout(request)
    return redirect('/ProjectManagement/login/')

@xframe_options_exempt
@login_required
def history_view(request, MODEL):
    print(request.user)
    if MODEL in models_dict:
        return render(request, 'ProjectManagement/history/'+MODEL+'_history.html', {'Station_list':Station.objects.all()})
    else:
        return Http404

def ajax_server(request):

    item_list = models_dict[request.POST['model']].objects.filter(Station__name=request.POST['station']) #筛选工位
    
    if request.POST['recent_time_range'] == "no_recent":
        start = int(time.mktime(time.strptime(request.POST['start'], time_pattern[1])))
        end = int(time.mktime(time.strptime(request.POST['end'], time_pattern[1])))

    else:
        try:
            end = item_list.last().date_time #数据库中最近的时间
        except:
            return JsonResponse({});
        if request.POST['recent_time_range'] == "one_hour":
            start = end - 3600;
        elif request.POST['recent_time_range'] == "one_day":
            start = end- 3600*24
        else:
            start = end-600

    time_data = []
    y_data = []
    item_list = item_list.filter(date_time__lte = end, date_time__gte=start)#筛选其他条件，前边的是时间早的
    
    if request.POST['model'] == 'PoolImg':
        for item in item_list:
            #y_data.append(item.value.name)
            time_data.append(item.date_time)#倒序
            #print(item.date_time)
        return JsonResponse({
            #'img_url_list':y_data,
            'timestamp_list':time_data,
            'start_time':datetime.datetime.fromtimestamp(start).strftime(time_pattern[3]),
            'end_time':datetime.datetime.fromtimestamp(end).strftime(time_pattern[3]),
        })

    
    for item in item_list:
        time_data.append(datetime.datetime.fromtimestamp(item.date_time).strftime(time_pattern[3]))#转化为固定的时间格式
        y_data.append(item.value)
    print(time_data[0]);
    return JsonResponse({
        'x':time_data,
        'y':y_data
    })

@xframe_options_exempt
@login_required
def real_time_view(request, MODEL):
    if MODEL in models_dict:
        return render(request, 'ProjectManagement/realtime/'+MODEL+'_real_time.html', {'Station_list':Station.objects.all()})



IWMS/ProjectManagement/templates/ProjectManagement/history/Current_history.html
{% extends 'ProjectManagement/history/history_base.html' %}
{% block title %}历史焊接电流查询{% endblock title %}
{%block h1%}历史焊接电流查询{%endblock h1%}
{% block hidden_imformation %} 
<p id="chart_title" hidden='hidden'>历史电流</p>
<p id="chart_series_name" hidden='hidden'>电流</p>
<p id="model" hidden='hidden'>Current</p>
{%endblock hidden_imformation%}

IWMS/ProjectManagement/templates/ProjectManagement/history/PoolImg_history.html
{% extends 'ProjectManagement/history/history_base.html' %}
{% block title %}历史熔池照片查询{% endblock title %}
{%block style%}
<style>
    input[type=range]::-webkit-slider-thumb {
        -webkit-appearance: none;
    }

    input[type=range]{
        width: 500px;
    }

    input[type=range]::-webkit-slider-runnable-track {
        height: 15px;
        border-radius: 10px; /*将轨道设为圆角的*/
        box-shadow: 0 1px 1px #def3f8, inset 0 .125em .125em #0d1112; /*轨道内置阴影效果*/
    }

    input[type=range]:focus {
        outline: none;
    }

    input[type=range]::-webkit-slider-thumb {
        -webkit-appearance: none;
        height: 25px;
        width: 25px;
        margin-top: -5px; /*使滑块超出轨道部分的偏移量相等*/
        background: #ffffff; 
        border-radius: 50%; /*外观设置为圆形*/
        border: solid 0.125em rgba(205, 224, 230, 0.5); /*设置边框*/
        box-shadow: 0 .125em .125em #3b4547; /*添加底部阴影*/
    }
</style>

{%endblock style%}}
{%block h1%}历史熔池照片查询{%endblock h1%}
{% block script %}
<script type="text/javascript">
    $(document).ready(function(){
        //设置ajax
       $.ajaxSetup({
           data: {csrfmiddlewaretoken: '{{ csrf_token }}' },
       });

       $('#searchbutton').click(on_searchbutton_click);
       $('#time_range').change(on_rangebar_value_changed);
       $('#begin').click(on_begin_button_click);
       $('#suspend').click(on_suspend_button_click);
       $('#stop').click(on_stop_button_click);

       var time_stamp; //保存ajax返回的时间戳列表
       var img_socket = new WebSocket("ws://"+window.location.host+"/ws/PoolImg/");
       //设置websocket
       var WebSocket_request_data = {
           model:"PoolImg",
           station:"",
       };
       img_socket.onmessage = function(text_data){
           var raw_data = JSON.parse(text_data.data);
           $("#poolimg").attr("src", "data:image/png;base64,"+raw_data.base64);
           $('#current_pos').html("当前位置："+getFormatedata(WebSocket_request_data.timestamp));
       };
        img_socket.onclose = function(){
            console.error("websocket is closed");
       };

       var len;
       var myinterval;
       var interval_count = 0;
       var set_range_flag = 0;
       
       function search_sql(post_data, url){
           $.post(url, post_data, function(res){
                if(res){
                    len = res.timestamp_list.length
                    //console.log(len);
                    time_stamp = res.timestamp_list;
                    $('#start_time').html("开始："+getFormatedata(res.timestamp_list[0]));
                    $('#end_time').html("结束："+getFormatedata(res.timestamp_list[len-1]));
                    //console.log(res.timestamp_list[len-1])
                    $('#time_range').attr({"max":len-1,});
                    WebSocket_request_data.timestamp = res.timestamp_list[0];
                    $('#time_range').val(0).trigger("change");
                    $('#current_pos').html("当前位置："+getFormatedata(res.timestamp_list[0]));
                }else{
                    alert("数据请求错误");
                }

           });
       };

       function on_searchbutton_click(){
           set_range_flag = 1;
           var data = {
                start: $('#startdate').val() + ' ' + $('#starttime').val(),
                end: $('#enddate').val() + ' ' + $('#endtime').val(),
                recent_time_range:$("input[name=recent_time_range]:checked").val(),
                station:$("input[name=Station]:checked").val(),
                model:"PoolImg" 
            };
            WebSocket_request_data.station=$("input[name=Station]:checked").val();
            //console.log(WebSocket_request_data);
            if(data.recent_time_range === 'no_recent'){
                if(data.start === ' ' ||  data.end === ' '){
                    alert("注意选择正确的时间");
                    return;
                }
            }
            if(!data.station){
                alert("请选择Station");
                return;
            }
            url = "{% url 'ProjectManagement:ajax_server' %}";
            search_sql(data, url);
       };

       function on_begin_button_click(){
           if(set_range_flag === 0){
               alert("请设定查询范围，并且点击查询按钮！！！")
               return;
           }
           if(interval_count === 0){
                myinterval = setInterval(function(){
                var rangebar_currentValue=Number($('#time_range').val());
                if(rangebar_currentValue === Number($('#time_range').attr('max'))){
                    on_suspend_button_click();
                }
                $('#time_range').val(rangebar_currentValue+1).trigger("change");
                    }, 100);
                interval_count = 1;
           }
       };

       function on_suspend_button_click(){
            if(set_range_flag === 0){
               alert("请设定查询范围，并且点击查询按钮！！！")
               return;
            }
            if(interval_count === 1){
               clearInterval(myinterval);
                interval_count = 0;
            }
        }

        function on_stop_button_click(){
            if(set_range_flag === 0){
               alert("请设定查询范围，并且点击查询按钮！！！");
               return;
           }
            if(interval_count === 1){
               clearInterval(myinterval);
                interval_count = 0;
           }
           $('#time_range').val(0).trigger("change");
        }

        function on_rangebar_value_changed(){
            var rangebar_currentValue=Number($('#time_range').val());
            WebSocket_request_data.timestamp = time_stamp[rangebar_currentValue];
            //console.log(WebSocket_request_data);
            img_socket.send(JSON.stringify(WebSocket_request_data));
        };

        function getFormatedata(timestamp_seconds){
            var date = new Date();
            date.setTime(timestamp_seconds*1000);
            return date.getFullYear()+"/"+(date.getUTCMonth()+1)+"/"+date.getDate()+ " "+date.getHours()+":"+date.getMinutes()+":"+date.getSeconds();
        };

    });

</script>
{% endblock script %}
{%block extra%}
    <p><b>熔池图片</b></p>
    <img id="poolimg" src="{{ MEDIA_URL }}poolimg_default/default.png" onerror="javascript:this.src='{{ MEDIA_URL }}history_poolimg/1.jpg'" width="300" height="250"/></br>
    <p id='current_pos'>当前位置：</p></br>
    <b id='start_time'>开始   </b><input id="time_range" type="range" min=0 max=100 step="1" ><b id='end_time'/>结束    </b></br>
    <button id="begin">开始</button><button id="suspend">暂停</button><button id='stop'>停止</button>
{%endblock extra%}}

IWMS/ProjectManagement/templates/ProjectManagement/history/Sound_history.html
{% extends 'ProjectManagement/history/history_base.html' %}
{% block title %}历史焊接声音查询{% endblock title %}
{%block h1%}历史焊接声音查询{%endblock h1%}
{% block hidden_imformation %} 
<p id="chart_title" hidden='hidden'>历史声音</p>
<p id="chart_series_name" hidden='hidden'>声音</p>
<p id="model" hidden='hidden'>Sound</p>
{%endblock hidden_imformation%}

IWMS/ProjectManagement/templates/ProjectManagement/history/Station_history.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>焊接工作台</title>
</head>
<body>
    <h1><center><b>焊接工作台查询</b></center></h1>
    
    <div>
        <ul>
        {% for station in Station_list%}
        <li><b>{{station.name}}</b></li>
        <p>{{station.description}}</p>
        {% endfor %}
        </ul>
    </div>
        
</body>
</html>

    

IWMS/ProjectManagement/templates/ProjectManagement/history/Voltage_history.html
{% extends 'ProjectManagement/history/history_base.html' %}
{% block title %}历史焊接电压查询{% endblock title %}
{%block h1%}历史焊接电压查询{%endblock h1%}
{% block hidden_imformation %} 
<p id="chart_title" hidden='hidden'>历史电压</p>
<p id="chart_series_name" hidden='hidden'>电压</p>
<p id="model" hidden='hidden'>Voltage</p>
{%endblock hidden_imformation%}

IWMS/ProjectManagement/templates/ProjectManagement/history/history_base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{% block title %} {% endblock title %}</title>
    {%block style%}{%endblock style%}
    <!-- 引入 echarts.js -->
    <script src="{% static 'ProjectManagement/js/echarts.min.js' %}"></script>
    <script src="{% static 'ProjectManagement/js/jquery-3.4.1.min.js' %}"></script>
    {% block script %}
    <script type="text/javascript">
        $(document).ready(function(){
        //设置ajax
        $.ajaxSetup({ 
            data: {csrfmiddlewaretoken: '{{ csrf_token }}' },
        });
        //初始化chart
        var myChart = echarts.init(document.getElementById('chart'));
        var option = {
            title: {
                text: $("#chart_title").html(), //改变
            },
            tooltip: {},
            legend: {
                //data:[$("#chart_legend").html()]//改变
            },
            xAxis: {
            },
            yAxis: {},
            series: [{
                name: $("#chart_series_name").html(),//改变
                type: 'line',
            }]
        };
        //myChart.showLoading();
        $('#searchbutton').click(on_searchbutton_click);
        
        function search_and_show(post_data, url){
            myChart.showLoading();
            $.post(url, post_data, function (res){
                if(res){
                    option.xAxis.data = res.x;
                    option.series[0].data = res.y;
                    //console.log(res.x);
                    myChart.hideLoading();
                    myChart.setOption(option);
                    
                }else{
                    alert("数据请求错误");
                    myChart.hideLoading();
                }
            });
        };

        function on_searchbutton_click(){

            var data = {
                start: $('#startdate').val() + ' ' + $('#starttime').val(),
                end: $('#enddate').val() + ' ' + $('#endtime').val(),
                recent_time_range:$("input[name=recent_time_range]:checked").val(),
                station:$("input[name=Station]:checked").val(),
                model:$("#model").html() //需要改变
            };
            
            if(data.recent_time_range === 'no_recent'){
                if(data.start === ' ' ||  data.end === ' '){
                    alert("注意选择正确的时间");
                    return;
                }
            }

            if(!data.station){
                alert("请选择Station");
                return;
            }
            url = "{% url 'ProjectManagement:ajax_server' %}";
            search_and_show(data, url);
        };
    });
    </script>
    {% endblock script %}
</head>

<body>
    <h1><center><b>{%block h1%}{%endblock h1%}</b></center></h1>
    <div id='search-block'>
        <center>
            <input type="date" id = 'startdate'></input><input id='starttime' type="time">开始时间</input>
            <input type="date" id = 'enddate'></input><input id='endtime' type="time">结束时间</input></br>
            <div id= 'recent'>
            <input type="radio" name="recent_time_range" value="no_recent" checked>不启用最近</input>
            <input type="radio" name="recent_time_range" value="one_day">最近一天</input>
            <input type="radio" name="recent_time_range" value="one_hour">最近一小时</input>
            <input type="radio" name="recent_time_range" value="ten_min">最近十分钟</input>
            </div></br>
            <div id = 'Station-option'>
                {% for station in Station_list %}
                <input type="radio" name="Station" value="{{station.name}}" />{{station.name}}
                {% endfor %}
            </div>
            <button id='searchbutton' >查询</button></br>
            {%block extra%}{%endblock extra%}
        </center>
    </div>
    
    {%block hidden_imformation %}{%endblock%}

    <center><div id="chart" style="width: 1200px;height:300px;"></div></center>
</body>

IWMS/ProjectManagement/templates/ProjectManagement/index.html
{% load static%}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<title>焊接数据查询平台</title>
		<script src="{% static 'ProjectManagement/js/jquery-3.4.1.min.js' %}"></script>
		<script type='text/javascript'>
			function select(button){
					$('#if_src').attr('src', button.attributes["href"].value);
				};
		</script>
        <style type='text/css'>
            *{
				padding:0px;
				margin:0px;
			}
			body{
				background-color:lightcyan;
			}

			#box{
				width:1200px;
				margin:0 auto;
				font-size:0;
			}
			#logo{
				height:50px;
				background-color:lightblue;
			}
			#nav{
				display:inline-block;
				width:200px;
				height:700px;
				background-color:burlywood;
				
			}
			#main{
				display:inline-block;
				width:1000px;
				height:700px;
				background-color:lightgoldenrodyellow;
				float:right;
				
			}
			#if_src{
				width:100%;
				height:100%;
				border-top-width: 0px;
    			border-right-width: 0px;
    			border-bottom-width: 0px;
    			border-left-width: 0px;
				border-style: inset;
			}
		</style>
	</head>
	<body>
		<div id='box'>
			<div id='logo'>
				<center><span style="font-size:30px">焊接数据查询平台</span></center>
			</div>
			<div id='nav'>
                <div style="font-size:15px;margin-left:20px;margin-top:100px;">
                    <p style="font-size:10px" >用户名：{{ user.username }}           <button><a href="{% url 'ProjectManagement:log_out' %}">注销</a></button></p>
                    <br>
                    <ul type='none'>
                        <p>历史数据查询</p>
                        <li><button onclick="select(this)" href="/ProjectManagement/history/Voltage">历史电压查询</button></li>
                        <li><button onclick="select(this)" href="/ProjectManagement/history/Current">历史电流查询</button></li>
                        <li><button onclick="select(this)" href="/ProjectManagement/history/Sound">历史声音查询</button></li>
                        <li><button onclick="select(this)" href="/ProjectManagement/history/PoolImg">历史熔池照片查询</button></li>
                        <br>
                        <p>实时数据查询</p>
                        <li><button onclick="select(this)" href="/ProjectManagement/real_time/Voltage">实时电压查询</button></li>
                        <li><button onclick="select(this)" href="/ProjectManagement/real_time/Current">实时电流查询</button></li>
                        <li><button onclick="select(this)" href="/ProjectManagement/real_time/Sound">实时声音查询</button></li>
                        <li><button onclick="select(this)" href="/ProjectManagement/real_time/PoolImg">实时熔池照片查询</button></li>
                        <br>
                        <p>工位信息</p>
                        <li><button onclick="select(this)" href="/ProjectManagement/history/Station">工位</button></li>
                    </ul>
                </div>
			</div>
            <div id='main'>
			<iframe id='if_src' src=""></iframe>
            
			</div>
		</div>
		
	</body>
</html>

IWMS/ProjectManagement/templates/ProjectManagement/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <style type='text/css'>
      *{
        background-image:url("{% static 'ProjectManagement/img/login_background.jpg' %}");
        background-size:cover;
      }
    </style>
</head>
<body>
<div class="container">
  <center>
  <form class="form-signin" action="{% url 'ProjectManagement:login_action' %}" method="post">
  {% csrf_token %} <!--csrf_token：生成令牌-->
    <h2 class="form-signin-heading" align="center">登录系统</h2>
    <label for="inputUsername" class="sr-only">username</label>
    <input type="text" name="username" id="inputUsername" class="form-control" placeholder="username" required autofocus></br>
    <label for="inputPassword" class="sr-only">Password</label>
    <input type="password" name="passwd" id="inputPassword" class="form-control" placeholder="Password" required></br>
    {% if error_massage%}
    <script>
      alert("{{error_massage}}");
    </script>
    {% else %}
    </br>
    {% endif %}
    <button class="btn btn-lg btn-primary btn-block" type="submit">登录</button>
  </form>
  </center>
</div>
</body>
</html>

IWMS/ProjectManagement/templates/ProjectManagement/realtime/Current_real_time.html
{% extends 'ProjectManagement/realtime/real_time_base.html' %}
{% block title %}焊接电流实时监控{% endblock title %}
{% block h1%}焊接电流实时监控{% endblock%}
{% block hidden %}
<p id="chart_title" hidden>焊接电流实时监控<p>
<p id="chart_series_name" hidden>焊接电流实时监控<p>
<p id="model" hidden>Current</p>
{% endblock %}

IWMS/ProjectManagement/templates/ProjectManagement/realtime/PoolImg_real_time.html
{% extends "ProjectManagement/realtime/real_time_base.html"%}
{% block title %}焊接熔池图像实时监控{% endblock title %}
{% block h1%}焊接熔池图像实时监控{% endblock%}
{% block script %}
<script type="text/javascript">
$(document).ready(function(){
    $('input[name=Station]:eq(0)').attr('checked','checked');
    var PoolImg_websocket = new WebSocket("ws://"+window.location.host+"/ws/real_time/");
    PoolImg_websocket.onmessage = function(res){
        var raw_data = JSON.parse(res.data);
        //console.log(raw_data);
        $("#poolimg").attr("src", "data:image/png;base64,"+raw_data.value);
        $('#current_pose').html("当前位置："+raw_data.date);
        $('#current_station').html("当前工位："+$("input:radio[name='Station']:checked").val())
    };

    PoolImg_websocket.onclose = function(){

    };

    $("input:radio[name='Station']").change(function(){

    });

    setInterval(function(){
        PoolImg_websocket.send(JSON.stringify({
                "Model":"PoolImg", //需要改变
                "station":$("input[name=Station]:checked").val()
            }))

    }, 300);

})
</script>
{% endblock %}
{% block extra %}
<p><b>熔池图片</b></p>
<img id="poolimg" src="{{ MEDIA_URL }}poolimg_default/default.png" onerror="javascript:this.src='{{ MEDIA_URL }}history_poolimg/1.jpg'" width="300" height="250"/></br>
<p id='current_pose'>当前位置：</p></br>
<p id ='current_station'>当前工位：</p></br>
{% endblock %}

IWMS/ProjectManagement/templates/ProjectManagement/realtime/Sound_real_time.html
{% extends 'ProjectManagement/realtime/real_time_base.html' %}
{% block title %}焊接声音实时监控{% endblock title %}
{% block h1%}焊接声音实时监控{% endblock%}
{% block hidden %}
<p id="chart_title" hidden>焊接声音实时监控<p>
<p id="chart_series_name" hidden>焊接声音实时监控<p>
<p id="model" hidden>Sound</p>
{% endblock %}

IWMS/ProjectManagement/templates/ProjectManagement/realtime/Voltage_real_time.html
{% extends 'ProjectManagement/realtime/real_time_base.html' %}
{% block title %}焊接电压实时监控{% endblock title %}
{% block h1%}焊接电压实时监控{% endblock%}
{% block hidden %}
<p id="chart_title" hidden>焊接电压实时监控<p>
<p id="chart_series_name" hidden>焊接电压实时监控<p>
<p id="model" hidden>Voltage</p>
{% endblock %}

IWMS/ProjectManagement/templates/ProjectManagement/realtime/real_time_base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{% block title %} {% endblock title %}</title>
    {% block style%}{% endblock style%}
    <!-- 引入 echarts.js -->
    <script src="{% static 'ProjectManagement/js/echarts.min.js' %}"></script>
    <script src="{% static 'ProjectManagement/js/jquery-3.4.1.min.js' %}"></script>
    {% block script %}
    <script type="text/javascript">
    $(document).ready(function(){
        var mychart = echarts.init(document.getElementById('chart'));
        
        $('input[name=Station]:eq(0)').attr('checked','checked');
        var data_len = 100;
        var x_data = [], y_data=[];

        var option = {
            title:{
                text:$("#chart_title").html(), //需要改变
            },
            tooltip:{},
            legend:{},
            xAxis:{
                data:[]
            },
            yAxis:{
                boundaryGap: [0, '100%'],
                plitLine: {
                    show: true
                }
            },
            series:[{
                name:$("#chart_series_name").html(), //需要改变
                type:'line',
                showSymbol: false,
                hoverAnimation: false,
            }]

        };
        mychart.setOption(option);
        var websocket = new WebSocket("ws://"+window.location.host+"/ws/real_time/"); //创建websocket
        websocket.onmessage = function(res){
            var raw_data = JSON.parse(res.data);
            //console.log(x_data);
            y_data.push(raw_data.value); 
            x_data.push(raw_data.date);
            
            if(y_data.length > data_len){
                y_data = y_data.slice(1, data_len+1);
                x_data = x_data.slice(1, data_len+1);
            }

            mychart.setOption({
                xAxis:{
                    data:x_data
                },
                series:[{
                    data:y_data
                }]
            });
        };

        websocket.onclose = function(){
            
        };

        $("input:radio[name='Station']").change(function(){
            y_data = [];
            x_data =[]
            mychart.setOption({
                xAxis:{
                    data:x_data
                },
                series:[{
                    data:y_data
                }]
            });
        });

        setInterval(function() {
            websocket.send(JSON.stringify({
                "Model":$("#model").html(), //需要改变
                "station":$("input[name=Station]:checked").val()
            }))
            
        }, 1500);//轮询

    });
    </script>
    {% endblock %}
</head>
<body>
    <center>
    <h1>{%block h1%}{%endblock%}</h1> 
    <div id="Station-Option">
        {% for station in Station_list %}
        <input type="radio" name="Station" value="{{station.name}}">{{station.name}}</input>
        {% endfor %}
    </div>
    <p></p>
    {% block extra %}{% endblock %}
    </center>
    {% block hidden %}{% endblock %}
    <center><div id="chart" style="width: 1200px;height:300px;"></div></center>
</body>
</html>